### ISSUE TITLE
Issue with the output (Not calculating the scientific calculation despite of giving the correct operation symbol).

### ISSUE THREAD

**Issue by iitanahem** [iitanahem/CPP#3]
file name: excercise1.cpp

<img width="951" alt="Screenshot 2024-02-20 at 8 31 00 AM" src="https://github.com/iitanahem/CPP/assets/63219546/1d0e1c76-b177-4842-b3f1-71da8a11fdd2">

To be _Fixed_ **ASAP**

**Comment by ayushk0** [comment]
Issue Fixed

Happy Coding :)
